Prefix: "&C&LC&A&LI&9&lD &r&8| "
IntegrationUrl: '' # Put here your Discord Webhook URL

EmbedOptions:
  Enabled: true # Set to false to disable embeds
  Color: "#000000" # Hex colors: #FFFFFF, #000000, etc.

Messages: # You can change the messages here, but you can't change the colors (yet)
  NoPermission: "You don't have permission to use this command."
  ReloadCommand: "Plugin reloaded."
  InvalidUsage: "Invalid usage. Type /chatindiscord for help."