Prefix: "&C&LC&A&LI&9&lD &r&8| "
IntegrationUrl: '' # Put here your Discord Webhook URL
DiscordEmbed: true # Set to false to disable embeds

Messages: # You can change the messages here, but you can't change the colors (yet)
  NoPermission: "You don't have permission to use this command."
  ReloadCommand: "Plugin reloaded."
  InvalidUsage: "Invalid usage. Type /chatindiscord for help."