# This is the plugin's global prefix.
# You can change this, but you don't have to.
Prefix: "&C&LC&A&LI&9&lD &r&8| "

# You can put multiple discord webhook URLs here.
# If you only use 1 or more, you can simply remove / add lines.
IntegrationUrls:
  - "https://discord-webhook-here"
  - "https://discord-webhook-here"

# These are the embed options, for discord embeds.
# You can turn this off if you want, but whatever you like better.
EmbedOptions:
  Enabled: true # Set to false to disable embeds
  Color: "#000000" # Hex colors: #FFFFFF, #000000, etc.

# You can change the messages here, but
# you can't change the colors (yet).
Messages:
  NoPermission: "You don't have permission to use this command."
  ReloadCommand: "Plugin reloaded."
  InvalidUsage: "Invalid usage. Type /chatindiscord for help."
  NotAllowed: "Using the @ symbol to mention players is not allowed."