name: Release Plugin

on:
  release:
    types:
      - created
  workflow_dispatch:
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build and Package
        run: mvn package -B

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/ChatInDiscord.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.event.release.tag_name }}
          draft: false
